name: rm
channels:
    - defaults
    - conda-forge
dependencies:
    - python>=3.9
    - pip
    - pip:
          - PyQt5>=5.15
          - matplotlib-backend-qtquick
    # numeric
    - numpy
    - nomkl
    - control
    - slycot
    - matplotlib-base=3.4
    - seaborn-base
    # misc
    - rich
    - loguru
    - click
    - pyyaml
    - cx_freeze>=6.9
    # dev
    - pytest
    - pylint
    - yapf
    - toml
    - isort
    - mypy