name: rm
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.9
    - pip
    - pip:
          - PyQt5>=5.15
          - matplotlib-backend-qtquick
    # numeric
    - numpy
    - nomkl
    - control
    - slycot
    - matplotlib-base
    - seaborn-base
    # misc
    - rich
    - loguru
    - click
    - pyyaml
    - cx_freeze
    # dev
    - pytest
    - pylint
    - yapf
    - toml
    - isort
    - mypy