name: rmpip
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - pip
  - pip:
    - pyside2>=5.15
    - pyqt5>=5.15
  - numpy
  - nomkl
  - control
  - slycot
  - matplotlib-base
  - seaborn
  - rich
  - loguru
  - cx_freeze
  - pytest
  - pylint
  - yapf
  - mypy
